### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'find_all'

### ISSUE THREAD

**Issue by Reza-Ardestani** [adashofdata/nlp-in-python-tutorial#13]
**It should be 'elementor-widget-theme-post-content' instead of 'post-content'**

I ran your code with python3 on Colab and I got some errors.

Error: 
<ipython-input-10-49e72183b92a> in transcriptMaker(url)
      8     page = requests.get(url).text
      9     soup = BeautifulSoup(page, "lxml")
---> 10     text = [p.text for p in soup.find(class_="post-content").find_all('p')]
     11     print(url)
     12     return text

AttributeError: 'NoneType' object has no attribute 'find_all'

Thanks for your great job

**Comment by sayuatm** [comment]
I guess they changed their layout.
Try `text = [p.text for p in soup.find(class_="elementor-element elementor-element-74af9a5b elementor-widget elementor-widget-theme-post-content").find_all('p')]`

**Comment by mr10101** [comment]
Hi,

I still get the same error. Are there any further adjustments that may be needed?
Many thanks and kind regards


---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-31-5306ff4c315f> in <module>
      1 # # Actually request transcripts (takes a few minutes to run)
----> 2 transcripts = [url_to_transcript(u) for u in urls]

<ipython-input-31-5306ff4c315f> in <listcomp>(.0)
      1 # # Actually request transcripts (takes a few minutes to run)
----> 2 transcripts = [url_to_transcript(u) for u in urls]

<ipython-input-30-b0e308bada49> in url_to_transcript(url)
      9     page = requests.get(url).text
     10     soup = BeautifulSoup(page, "lxml")
---> 11     text = [p.text for p in soup.find(class_="elementor-element elementor-element-74af9a5b elementor-widget elementor-widget-theme-post-content").find_all('p')]
     12     print(url)
     13     return text

AttributeError: 'NoneType' object has no attribute 'find_all'

**Comment by gobinaryn** [comment]
Hi, as of 30 May 2021 the code text = [p.text for p in soup.find(class_="site-content").find_all('p')] works for this. change the word post to site so the class reads "site-content"

**Comment by adashofdata** [comment]
The most recent code has class_="ast-container" and it now works.
