### ISSUE TITLE
.nonzero() is deprecated

### ISSUE THREAD

**Issue by dcgonzalez001** [adashofdata/nlp-in-python-tutorial#2]
## Context
I went through this tutorial on 2019-07-06 with vanilla installs of recommended software applications and updates on a Windows 10 Home x64 machine and encountered a deprecation warning when running 2-Exploratory-Data-Analysis.ipynb in the jupyter notebook.
## Issue
`Series.nonzero()` is deprecated and will be removed in a future version.  
## Solution
Update code in 2-Exploratory-Data-Analysis.ipynb from original:
```python
uniques = data[comedian].nonzero()[0].size
```
to 
```python
# uniques = data[comedian].nonzero()[0].size (deprecated)
uniques = data[comedian].to_numpy().nonzero()[0].size
```

**Comment by scalasm** [comment]
Well, on 1st April 2020, I can confirm that it has been removed so that step doesn't work anymore and must be changed as explained.
