### ISSUE TITLE
ymin and ymax in Matplotlib are deprecated

### ISSUE THREAD

**Issue by dcgonzalez001** [adashofdata/nlp-in-python-tutorial#3]
## Context
I went through this tutorial on 2019-07-07 with vanilla installs of recommended software applications and updates on a Windows 10 Home x64 machine and encountered a deprecation warning when running 3-Sentiment-Analysis.ipynb in the jupyter notebook.
## Issues
The `ymin` argument was deprecated in Matplotlib 3.0 and will be removed in 3.2.
The `ymax` argument was deprecated in Matplotlib 3.0 and will be removed in 3.2.
## Solution
Update code in 3-Sentiment-Analysis.ipynb from original:
```python
plt.ylim(ymin=-.2, ymax=.3)
```
to 
```python
# plt.ylim(ymin=-.2, ymax=.3) (deprecated)
plt.ylim(bottom=-.2, top=.3)
```

**Comment by adashofdata** [comment]
Updated the code. Thanks for logging this issue!
