### ISSUE TITLE
Getting this error- Need Help

### ISSUE THREAD

**Issue by AlienCommunication** [adashofdata/nlp-in-python-tutorial#4]
When i run this code (From one of your python file comparing comedians) while scraping data from urls 
--------------------------
# Load pickled files
data = {}
for i, c in enumerate(comedians):
    with open("transcripts/" + c + ".txt", "rb") as file:
        data[c] = pickle.load(file)

---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-11-989355157330> in <module>
      2 data = {}
      3 for i, c in enumerate(comedians):
----> 4     with open("transcripts/" + c + ".txt", "rb") as file:
      5         data[c] = pickle.load(file)

FileNotFoundError: [Errno 2] No such file or directory: 'transcripts/louis.txt'

**Comment by AlienCommunication** [comment]
Can somebody help me? @adashofdata

**Comment by ChahineB** [comment]
you need to create a folder in your directory 'transcripts' and put all transcript  '.txt' files in it.

**Comment by amer306** [comment]
!mkdir transcripts

**Comment by srfmstr** [comment]
on windows you have to create directory called transcripts on c:\ drive 
c:\transcripts. I was able to compile the whole project without any issues.

**Comment by edwardleeeee** [comment]
> you need to create a folder in your directory 'transcripts' and put all transcript '.txt' files in it.

May I know how to put all transcript '.txt' files in it? Thank you! I already created the folder but not sure how to automatically scrape the content, transferred it into .txt files and automatically appear in that folder.

**Comment by VedantMadane** [comment]
I'm running it in colab and having the same issue.

**Comment by amnanafees** [comment]
#import pickle
# # Pickle files for later use

# # Make a new directory to hold the text files
!mkdir transcripts                                                                 
for i, c in enumerate(comedians):
    with open("transcripts/" + c + ".txt", "wb") as file:
        pickle.dump(transcripts[i], file)


#!mkdir transcripts(please uncoment it)then it will work in line 4

**Comment by adashofdata** [comment]
Closing this thread since the question has been answered.
