### ISSUE TITLE
Getting some parser error in BeautifulSoup

### ISSUE THREAD

**Issue by iamharshgoel** [adashofdata/nlp-in-python-tutorial#8]
FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?
![Screenshot (4631)](https://user-images.githubusercontent.com/41647099/83793002-86443900-a6b9-11ea-98c1-fc7ff25cc352.png)

**Comment by bparikh99** [comment]
yes you have to download lxml via pip install lxml

**Comment by md-sid** [comment]
You have to change the **class_="post-content"** part to **class_="elementor-element elementor-element-74af9a5b elementor-widget elementor-widget-theme-post-content"**

**Comment by gobinaryn** [comment]
Hi, as of 30 May 2021 and alternatively the code text = [p.text for p in soup.find(class_="site-content").find_all('p')] works for this. change the word post to site so the class reads "site-content"

**Comment by adashofdata** [comment]
The most recent code has class_="ast-container" and it now works.
